-- MILESTONE: 01
-- OBJECT: usp_replicate_po_header
-- DESCRIPTION: Replicate PO Header from MED/GP POD10100 to h_po_header
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_po_header
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.h_po_header (
        PONUMBER, POSTATUS, VENDORID, VENDNAME, DOCAMNT,
        CURNCYID, ORSOURCEDOC, ORSOURCEREF, REQDATETIME, DUEDATE,
        SHIPMTHD, PAYMTHID, PRCLEVEL, DATERECD, REFTONMBRS,
        BCKTYEAR_I, BCKTPERIOD_I, DATETIMESTAMP
    )
    SELECT
        PONUMBER, POSTATUS, VENDORID, VENDNAME, DOCAMNT,
        CURNCYID, ORSOURCEDOC, ORSOURCEREF, REQDATETIME, DUEDATE,
        SHIPMTHD, PAYMTHID, PRCLEVEL, DATERECD, REFTONMBRS,
        BCKTYEAR_I, BCKTPERIOD_I, GETUTCDATE()
    FROM dbo.POD10100
    WHERE POSTATUS > 0;

    EXEC dbo.usp_rep_log 'REPLICATE', 'usp_replicate_po_header', 'SUCCESS';
END
GO