-- MILESTONE: 01
-- OBJECT: usp_replicate_po_header
-- DESCRIPTION: Replicate PO Header (POD10100) into h_po_header. Append-only.
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_po_header
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.h_po_header
    (
        PONUMBER, POSTATUS, VENDORID, VENDNAME, DOCAMNT, CURNCYID,
        ORSOURCEDOC, ORSOURCEREF, REQDATETIME, DUEDATE, SHIPMTHD, PAYMTHID,
        PRCLEVEL, DATERECD, REFTONMBRS, BCKTYEAR_I, BCKTPERIOD_I,
        CREATEDDATETIME, MODIFIEDDATETIME, DATETIMESTAMP
    )
    SELECT
        src.PONUMBER, src.POSTATUS, src.VENDORID, src.VENDNAME, src.DOCAMNT, src.CURNCYID,
        src.ORSOURCEDOC, src.ORSOURCEREF, src.REQDATETIME, src.DUEDATE, src.SHIPMTHD, src.PAYMTHID,
        src.PRCLEVEL, src.DATERECD, src.REFTONMBRS, src.BCKTYEAR_I, src.BCKTPERIOD_I,
        src.CREATEDDATETIME, src.MODIFIEDDATETIME, GETUTCDATE()
    FROM dbo.POD10100 AS src
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.h_po_header AS tgt
        WHERE tgt.PONUMBER = src.PONUMBER
    );

    EXEC dbo.usp_rep_log;
END
GO