-- MILESTONE: 01
-- OBJECT: usp_replicate_lots
-- DESCRIPTION: Replicate Lot Master from LOTMAST
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_lots
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH config AS (
        SELECT NONINVEN = 0
    )

    INSERT INTO dbo.h_lot_master (
        LOTNUMBR, ITEMNMBR, LOCNCODE, LOTATTRIBUTE1, LOTATTRIBUTE2,
        LOTATTRIBUTE3, TRK_LOT_USERDEF_1, TRK_LOT_USERDEF_2,
        QUANTITY, DATERECD, DUEDATE, EXPDATE, LOTSTATUS, HOLDSTS,
        DATETIMESTAMP
    )
    SELECT
        LOTNUMBR, ITEMNMBR, LOCNCODE, LOTATTRIBUTE1, LOTATTRIBUTE2,
        LOTATTRIBUTE3, TRK_LOT_USERDEF_1, TRK_LOT_USERDEF_2,
        QUANTITY, DATERECD, DUEDATE, EXPDATE, LOTSTATUS, HOLDSTS,
        GETUTCDATE()
    FROM dbo.LOTMAST;

    EXEC dbo.usp_rep_log 'REPLICATE', 'usp_replicate_lots', 'SUCCESS';
END
GO