-- MILESTONE: 01
-- OBJECT: usp_replicate_items
-- DESCRIPTION: Replicate Item Master (IV00101), Item Qty (IV00102), and Item-Vendor Xref (IV00103).
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_items
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH config AS (
        SELECT NONINVEN = 0
    )

    -- Item Master
    INSERT INTO dbo.h_item_master
    (
        ITEMNMBR, ITEMDESC, ITMSHNAM, ITEMSHWT, ITMSHWTUOM, STNDCOST, CURRCOST,
        ITEMSHWTDSCR, DECPLQTY, DECPLCUR, ITEMSCHCAT_I, ITEMTYPE, INACTIVE,
        STKAVLBL, COMMCODE_I, TAXOPTNS, IVCOGSIX, IVSLSIDX, IVALIASIX, IVVARIX,
        MSTRCDTY, MODIFDT, CREATEDDT, DATETIMESTAMP
    )
    SELECT
        src.ITEMNMBR, src.ITEMDESC, src.ITMSHNAM, src.ITEMSHWT, src.ITMSHWTUOM, src.STNDCOST, src.CURRCOST,
        src.ITEMSHWTDSCR, src.DECPLQTY, src.DECPLCUR, src.ITEMSCHCAT_I, src.ITEMTYPE, src.INACTIVE,
        src.STKAVLBL, src.COMMCODE_I, src.TAXOPTNS, src.IVCOGSIX, src.IVSLSIDX, src.IVALIASIX, src.IVVARIX,
        src.MSTRCDTY, src.MODIFDT, src.CREATEDDT, GETUTCDATE()
    FROM dbo.IV00101 AS src
    CROSS JOIN config
    WHERE src.NONINVEN = config.NONINVEN
      AND NOT EXISTS (
          SELECT 1 FROM dbo.h_item_master AS tgt WHERE tgt.ITEMNMBR = src.ITEMNMBR
      );

    -- Item Qty
    INSERT INTO dbo.h_item_qty
    (
        ITEMNMBR, LOCNCODE, UOFM, QTYTYPE, TRK_LOT_USERDEF_1, TRK_LOT_USERDEF_2,
        ATYALLOC, QTYONHND, QTYINSPECT, QTYINUSE, QTYDMGED, QTYRSVD,
        QTYBACKORD, QTYAVAIL, DECPLQTY, EXCESSALLOCQTY_I, ALLOCABAL, DATETIMESTAMP
    )
    SELECT
        src.ITEMNMBR, src.LOCNCODE, src.UOFM, src.QTYTYPE, src.TRK_LOT_USERDEF_1, src.TRK_LOT_USERDEF_2,
        src.ATYALLOC, src.QTYONHND, src.QTYINSPECT, src.QTYINUSE, src.QTYDMGED, src.QTYRSVD,
        src.QTYBACKORD, src.QTYAVAIL, src.DECPLQTY, src.EXCESSALLOCQTY_I, src.ALLOCABAL, GETUTCDATE()
    FROM dbo.IV00102 AS src
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.h_item_qty AS tgt
        WHERE tgt.ITEMNMBR = src.ITEMNMBR AND tgt.LOCNCODE = src.LOCNCODE
          AND tgt.UOFM = src.UOFM AND tgt.QTYTYPE = src.QTYTYPE
    );

    -- Item-Vendor Xref
    INSERT INTO dbo.h_item_vendor_xref
    (
        VENDORID, ITEMNMBR, VENDNAME, ITMVNPNMBR, ITEMDESC, CURRCOST,
        DECPLCUR, LEADTIME, MINORDERQTY, MAXORDERQTY, ECONORDERQTY, PRIMARYVENDOR,
        VNDPRCTNM, UOFM, DATETIMESTAMP
    )
    SELECT
        src.VENDORID, src.ITEMNMBR, src.VENDNAME, src.ITMVNPNMBR, src.ITEMDESC, src.CURRCOST,
        src.DECPLCUR, src.LEADTIME, src.MINORDERQTY, src.MAXORDERQTY, src.ECONORDERQTY, src.PRIMARYVENDOR,
        src.VNDPRCTNM, src.UOFM, GETUTCDATE()
    FROM dbo.IV00103 AS src
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.h_item_vendor_xref AS tgt
        WHERE tgt.VENDORID = src.VENDORID AND tgt.ITEMNMBR = src.ITEMNMBR
    );

    EXEC dbo.usp_rep_log;
END
GO