-- MILESTONE: 01
-- OBJECT: usp_replicate_mo_picklist
-- DESCRIPTION: Replicate MO Picklist from MED/GP WO010302 to h_mo_picklist
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_mo_picklist
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH config AS (
        SELECT ActiveMOStatus1 = 2, ActiveMOStatus2 = 3, NONINVEN = 0
    )

    INSERT INTO dbo.h_mo_picklist (
        PICKLISTNUMBER, MANUFACTUREORDER_I, WORKORDERNUMBER, LOCNCODE,
        QUANTITY, ITEMNMBR, UOFM, DUEDATE, STATUS, SUPPLIERID,
        PURCHASEORDER_I, PURCHASEORDERLN_I, MILESTONEVALUE, MILESTONEDATE,
        REVISION, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3, DATETIMESTAMP
    )
    SELECT
        PICKLISTNUMBER, MANUFACTUREORDER_I, WORKORDERNUMBER, LOCNCODE,
        QUANTITY, ITEMNMBR, UOFM, DUEDATE, STATUS, SUPPLIERID,
        PURCHASEORDER_I, PURCHASEORDERLN_I, MILESTONEVALUE, MILESTONEDATE,
        REVISION, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3, GETUTCDATE()
    FROM dbo.WO010302
    WHERE STATUS IN (SELECT ActiveMOStatus1 FROM config UNION ALL SELECT ActiveMOStatus2 FROM config)
      AND MANUFACTUREORDER_I NOT IN (5, 6);

    EXEC dbo.usp_rep_log 'REPLICATE', 'usp_replicate_mo_picklist', 'SUCCESS';
END
GO