-- MILESTONE: 01
-- OBJECT: usp_replicate_po_detail
-- DESCRIPTION: Replicate PO Detail from MED/GP POD10110 to h_po_detail
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_po_detail
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.h_po_detail (
        PONUMBER, POLNESTA, ITEMNMBR, ITEMDESC, LOCNCODE,
        UOFM, QTYORDER, QTYRCVD, QTYCANCE, QTYUNCMTBASE,
        UNITCOST, EXTDCOST, REQDATETIME, DUEDATE, TRACK,
        MILESTONEVALUE, MILESTONEDATE, REFTONMBRS, POSTATUS, ORD,
        BCKTYEAR_I, BCKTPERIOD_I, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3,
        DATETIMESTAMP
    )
    SELECT
        PONUMBER, POLNESTA, ITEMNMBR, ITEMDESC, LOCNCODE,
        UOFM, QTYORDER, QTYRCVD, QTYCANCE, QTYUNCMTBASE,
        UNITCOST, EXTDCOST, REQDATETIME, DUEDATE, TRACK,
        MILESTONEVALUE, MILESTONEDATE, REFTONMBRS, POSTATUS, ORD,
        BCKTYEAR_I, BCKTPERIOD_I, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3,
        GETUTCDATE()
    FROM dbo.POD10110;

    EXEC dbo.usp_rep_log 'REPLICATE', 'usp_replicate_po_detail', 'SUCCESS';
END
GO