-- MILESTONE: 01
-- OBJECT: usp_replicate_mo_picklist
-- DESCRIPTION: Replicate MO Picklist from MED/GP WO010302 to h_mo_picklist
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_mo_picklist
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH config AS (
        SELECT ActiveMOStatus1 = 2, ActiveMOStatus2 = 3, NONINVEN = 0
    )

    INSERT INTO dbo.h_mo_picklist (
        PICKLISTNUMBER, MANUFACTUREORDER_I, WORKORDERNUMBER, LOCNCODE,
        QUANTITY, ITEMNMBR, UOFM, DUEDATE, STATUS, BINREFERENCE,
        CREATEDDATETIME, MODIFIEDDATETIME, SUPPLIERID,
        PURCHASEORDER_I, PURCHASEORDERLN_I, MILESTONEVALUE, MILESTONEDATE,
        REVISION, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3, DATETIMESTAMP
    )
    SELECT
        src.PICKLISTNUMBER, src.MANUFACTUREORDER_I, src.WORKORDERNUMBER, src.LOCNCODE,
        src.QUANTITY, src.ITEMNMBR, src.UOFM, src.DUEDATE, src.STATUS, src.BINREFERENCE,
        src.CREATEDDATETIME, src.MODIFIEDDATETIME, src.SUPPLIERID,
        src.PURCHASEORDER_I, src.PURCHASEORDERLN_I, src.MILESTONEVALUE, src.MILESTONEDATE,
        src.REVISION, src.LOTATTRIBUTE1, src.LOTATTRIBUTE2, src.LOTATTRIBUTE3, GETUTCDATE()
    FROM dbo.WO010302 AS src
    CROSS JOIN config
    WHERE src.STATUS IN (config.mo_status_active, config.mo_status_released)
      AND NOT EXISTS (
          SELECT 1
          FROM dbo.h_mo_picklist AS tgt
          WHERE tgt.PICKLISTNUMBER = src.PICKLISTNUMBER
            AND tgt.MANUFACTUREORDER_I = src.MANUFACTUREORDER_I
      );

    EXEC dbo.usp_rep_log;
END
GO