-- MILESTONE: 01
-- OBJECT: usp_replicate_bom
-- DESCRIPTION: Replicate BOM master and components from BM00101 and BM00111
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_bom
AS
BEGIN
    SET NOCOUNT ON;

    -- BOM Master
    INSERT INTO dbo.h_bom_master (
        BILLTYPE_I, WORKORDERNUMBER, ITEMNMBR, REVNO_I, BOMNOTE_I,
        LOWLEVEL, UOFM, QTYORDER, DATERECD, REFTONMBRS,
        BCKTYEAR_I, BCKTPERIOD_I, CREATEDDATETIME, MODIFDT, DATETIMESTAMP
    )
    SELECT
        BILLTYPE_I, WORKORDERNUMBER, ITEMNMBR, REVNO_I, BOMNOTE_I,
        LOWLEVEL, UOFM, QTYORDER, DATERECD, REFTONMBRS,
        BCKTYEAR_I, BCKTPERIOD_I, CREATEDDATETIME, MODIFDT, GETUTCDATE()
    FROM dbo.BM00101;

    -- BOM Component
    INSERT INTO dbo.h_bom_component (
        BILLTYPE_I, WORKORDERNUMBER, ITEMNMBR, COMPONENTITEM, REVNO_I,
        OPRNSEQNC_I, QUANTITY, UOFM, LOTATTRIBUTE1, LOTATTRIBUTE2,
        LOTATTRIBUTE3, TRACK, SCRAPAMNT, BCKTYEAR_I, BCKTPERIOD_I,
        DATETIMESTAMP
    )
    SELECT
        BILLTYPE_I, WORKORDERNUMBER, ITEMNMBR, COMPONENTITEM, REVNO_I,
        OPRNSEQNC_I, QUANTITY, UOFM, LOTATTRIBUTE1, LOTATTRIBUTE2,
        LOTATTRIBUTE3, TRACK, SCRAPAMNT, BCKTYEAR_I, BCKTPERIOD_I,
        GETUTCDATE()
    FROM dbo.BM00111;

    EXEC dbo.usp_rep_log 'REPLICATE', 'usp_replicate_bom', 'SUCCESS';
END
GO