-- MILESTONE: 01
-- OBJECT: usp_replicate_mo_header
-- DESCRIPTION: Replicate MO Header from MED/GP MOP10100 to h_mo_header
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_mo_header
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH config AS (
        SELECT ActiveMOStatus1 = 2, ActiveMOStatus2 = 3, NONINVEN = 0
    )

    INSERT INTO dbo.h_mo_header (
        MANUFACTUREORDER_I, WORKORDERNUMBER, STATUS, MANUFACTUREORDERT,
        ITEMNMBR, LOCNCODE, DUEDATE, STARTDATE, TRACK, FGIINDX, FGNINDX,
        SCRAPAMNT, SOURCERES_I, QTYORDER, QTYREMAINING, QTYCOMPLETED,
        QTYREJECTED, DATERECD, REFTONMBRS, BCKTYEAR_I, BCKTPERIOD_I,
        REVISION, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3, DATETIMESTAMP
    )
    SELECT
        MANUFACTUREORDER_I, WORKORDERNUMBER, STATUS, MANUFACTUREORDERT,
        ITEMNMBR, LOCNCODE, DUEDATE, STARTDATE, TRACK, FGIINDX, FGNINDX,
        SCRAPAMNT, SOURCERES_I, QTYORDER, QTYREMAINING, QTYCOMPLETED,
        QTYREJECTED, DATERECD, REFTONMBRS, BCKTYEAR_I, BCKTPERIOD_I,
        REVISION, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3, GETUTCDATE()
    FROM dbo.MOP10100
    WHERE STATUS IN (SELECT ActiveMOStatus1 FROM config UNION ALL SELECT ActiveMOStatus2 FROM config);

    EXEC dbo.usp_rep_log 'REPLICATE', 'usp_replicate_mo_header', 'SUCCESS';
END
GO