-- MILESTONE: 01
-- OBJECT: usp_replicate_vendor
-- DESCRIPTION: Replicate Vendor Master (PM00200) into h_vendor_master.
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_vendor
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.h_vendor_master
    (
        VENDORID, VENDNAME, VNDCLSID, VNDSTID, VNDSTNUM, VNDPHNUM, VNDFAX,
        VNDCRCRD, CURNCYID, INACTIVE, MINPYMTTYP, MINPYDLRNT, MAXPYMTTYP,
        PYMTRMID, CHKACTINDX, CREATEDDATETIME, MODIFIEDDATETIME, DATETIMESTAMP
    )
    SELECT
        src.VENDORID, src.VENDNAME, src.VNDCLSID, src.VNDSTID, src.VNDSTNUM, src.VNDPHNUM, src.VNDFAX,
        src.VNDCRCRD, src.CURNCYID, src.INACTIVE, src.MINPYMTTYP, src.MINPYDLRNT, src.MAXPYMTTYP,
        src.PYMTRMID, src.CHKACTINDX, src.CREATEDDATETIME, src.MODIFIEDDATETIME, GETUTCDATE()
    FROM dbo.PM00200 AS src
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.h_vendor_master AS tgt WHERE tgt.VENDORID = src.VENDORID
    );

    EXEC dbo.usp_rep_log;
END
GO