-- MILESTONE: 01
-- OBJECT: usp_replicate_po_detail
-- DESCRIPTION: Replicate PO Detail (POD10110) into h_po_detail. Append-only.
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_po_detail
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.h_po_detail
    (
        PONUMBER, POLNESTA, ITEMNMBR, ITEMDESC, LOCNCODE, UOFM,
        QTYORDER, QTYRCVD, QTYCANCE, QTYUNCMTBASE, UNITCOST, EXTDCOST,
        REQDATETIME, DUEDATE, TRACK, MILESTONEVALUE, MILESTONEDATE,
        REFTONMBRS, POSTATUS, ORD, BCKTYEAR_I, BCKTPERIOD_I,
        LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3, DATETIMESTAMP
    )
    SELECT
        src.PONUMBER, src.POLNESTA, src.ITEMNMBR, src.ITEMDESC, src.LOCNCODE, src.UOFM,
        src.QTYORDER, src.QTYRCVD, src.QTYCANCE, src.QTYUNCMTBASE, src.UNITCOST, src.EXTDCOST,
        src.REQDATETIME, src.DUEDATE, src.TRACK, src.MILESTONEVALUE, src.MILESTONEDATE,
        src.REFTONMBRS, src.POSTATUS, src.ORD, src.BCKTYEAR_I, src.BCKTPERIOD_I,
        src.LOTATTRIBUTE1, src.LOTATTRIBUTE2, src.LOTATTRIBUTE3, GETUTCDATE()
    FROM dbo.POD10110 AS src
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.h_po_detail AS tgt
        WHERE tgt.PONUMBER = src.PONUMBER AND tgt.POLNESTA = src.POLNESTA
    );

    EXEC dbo.usp_rep_log;
END
GO