-- MILESTONE: 01
-- OBJECT: usp_replicate_items
-- DESCRIPTION: Replicate Items (IV00101), Qty (IV00102), and Vendor Xref (IV00103)
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_items
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH config AS (
        SELECT NONINVEN = 0
    )

    -- Item Master
    INSERT INTO dbo.h_item_master (
        ITEMNMBR, ITEMDESC, ITMSHNAM, ITEMSHWT, ITMSHWTUOM,
        STNDCOST, CURRCOST, ITEMSHWTDSCR, DECPLQTY, DECPLCUR,
        ITMSCHCAT_I, ITEMTYPE, INACTIVE, STKAVLBL, COMMCODE_I,
        TAXOPTNS, IVCOGSIX, IVSLSIDX, IVALIASIX, IVVARIX,
        MSTRCDTY, MODIFDT, CREATEDDT, DATETIMESTAMP
    )
    SELECT
        ITEMNMBR, ITEMDESC, ITMSHNAM, ITEMSHWT, ITMSHWTUOM,
        STNDCOST, CURRCOST, ITEMSHWTDSCR, DECPLQTY, DECPLCUR,
        ITMSCHCAT_I, ITEMTYPE, INACTIVE, STKAVLBL, COMMCODE_I,
        TAXOPTNS, IVCOGSIX, IVSLSIDX, IVALIASIX, IVVARIX,
        MSTRCDTY, MODIFDT, CREATEDDT, GETUTCDATE()
    FROM dbo.IV00101
    WHERE NONINVEN = 0;

    -- Item Qty
    INSERT INTO dbo.h_item_qty (
        ITEMNMBR, LOCNCODE, UOFM, QTYTYPE, TRK_LOT_USERDEF_1,
        TRK_LOT_USERDEF_2, ATYALLOC, QTYONHND, QTYINSPECT,
        QTYINUSE, QTYDMGED, QTYRSVD, QTYBACKORD, QTYAVAIL,
        DECPLQTY, EXCESSALLOCQTY_I, ALLOCABAL, DATETIMESTAMP
    )
    SELECT
        ITEMNMBR, LOCNCODE, UOFM, QTYTYPE, TRK_LOT_USERDEF_1,
        TRK_LOT_USERDEF_2, ATYALLOC, QTYONHND, QTYINSPECT,
        QTYINUSE, QTYDMGED, QTYRSVD, QTYBACKORD, QTYAVAIL,
        DECPLQTY, EXCESSALLOCQTY_I, ALLOCABAL, GETUTCDATE()
    FROM dbo.IV00102;

    -- Item-Vendor Xref
    INSERT INTO dbo.h_item_vendor_xref (
        VENDORID, ITEMNMBR, VENDNAME, ITMVNPNMBR, ITEMDESC,
        CURRCOST, DECPLCUR, LEADTIME, MINORDERQTY, MAXORDERQTY,
        ECONORDERQTY, PRIMARYVENDOR, VNDPRCTNM, UOFM, DATETIMESTAMP
    )
    SELECT
        VENDORID, ITEMNMBR, VENDNAME, ITMVNPNMBR, ITEMDESC,
        CURRCOST, DECPLCUR, LEADTIME, MINORDERQTY, MAXORDERQTY,
        ECONORDERQTY, PRIMARYVENDOR, VNDPRCTNM, UOFM, GETUTCDATE()
    FROM dbo.IV00103;

    EXEC dbo.usp_rep_log 'REPLICATE', 'usp_replicate_items', 'SUCCESS';
END
GO