-- MILESTONE: 01
-- OBJECT: usp_replicate_bom
-- DESCRIPTION: Replicate Bill of Materials master (BM00101) and components (BM00111).
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_bom
AS
BEGIN
    SET NOCOUNT ON;

    -- BOM Master
    INSERT INTO dbo.h_bom_master
    (
        BILLTYPE_I, WORKORDERNUMBER, ITEMNMBR, REVNO_I, BOMNOTE_I, LOWLEVEL, UOFM,
        QTYORDER, DATERECD, REFTONMBRS, BCKTYEAR_I, BCKTPERIOD_I,
        CREATEDDATETIME, MODIFIEDDATETIME, DATETIMESTAMP
    )
    SELECT
        src.BILLTYPE_I, src.WORKORDERNUMBER, src.ITEMNMBR, src.REVNO_I, src.BOMNOTE_I, src.LOWLEVEL, src.UOFM,
        src.QTYORDER, src.DATERECD, src.REFTONMBRS, src.BCKTYEAR_I, src.BCKTPERIOD_I,
        src.CREATEDDATETIME, src.MODIFIEDDATETIME, GETUTCDATE()
    FROM dbo.BM00101 AS src
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.h_bom_master AS tgt
        WHERE tgt.BILLTYPE_I = src.BILLTYPE_I AND tgt.WORKORDERNUMBER = src.WORKORDERNUMBER
          AND tgt.ITEMNMBR = src.ITEMNMBR AND tgt.REVNO_I = src.REVNO_I
    );

    -- BOM Component
    INSERT INTO dbo.h_bom_component
    (
        BILLTYPE_I, WORKORDERNUMBER, ITEMNMBR, COMPONENTITEM, REVNO_I, OPRNSEQNC_I,
        QUANTITY, UOFM, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3, TRACK,
        SCRAPAMNT, BCKTYEAR_I, BCKTPERIOD_I, DATETIMESTAMP
    )
    SELECT
        src.BILLTYPE_I, src.WORKORDERNUMBER, src.ITEMNMBR, src.COMPONENTITEM, src.REVNO_I, src.OPRNSEQNC_I,
        src.QUANTITY, src.UOFM, src.LOTATTRIBUTE1, src.LOTATTRIBUTE2, src.LOTATTRIBUTE3, src.TRACK,
        src.SCRAPAMNT, src.BCKTYEAR_I, src.BCKTPERIOD_I, GETUTCDATE()
    FROM dbo.BM00111 AS src
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.h_bom_component AS tgt
        WHERE tgt.BILLTYPE_I = src.BILLTYPE_I AND tgt.WORKORDERNUMBER = src.WORKORDERNUMBER
          AND tgt.ITEMNMBR = src.ITEMNMBR AND tgt.COMPONENTITEM = src.COMPONENTITEM
          AND tgt.REVNO_I = src.REVNO_I AND tgt.OPRNSEQNC_I = src.OPRNSEQNC_I
    );

    EXEC dbo.usp_rep_log;
END
GO