-- MILESTONE: 01
-- OBJECT: usp_replicate_vendor
-- DESCRIPTION: Replicate Vendor Master from PM00200
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_vendor
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.h_vendor_master (
        VENDORID, VENDNAME, VNDCLSID, VNDSTID, VNDSTNUM,
        VNDPHNUM, VNDFAX, VNDCRCRD, CURNCYID, INACTIVE,
        MINPYMTTYP, MINPYDLRNT, MAXPYMTTYP, PYMTRMID, CHKACTINDX,
        DATETIMESTAMP
    )
    SELECT
        VENDORID, VENDNAME, VNDCLSID, VNDSTID, VNDSTNUM,
        VNDPHNUM, VNDFAX, VNDCRCRD, CURNCYID, INACTIVE,
        MINPYMTTYP, MINPYDLRNT, MAXPYMTTYP, PYMTRMID, CHKACTINDX,
        GETUTCDATE()
    FROM dbo.PM00200;

    EXEC dbo.usp_rep_log 'REPLICATE', 'usp_replicate_vendor', 'SUCCESS';
END
GO