-- MILESTONE: 01
-- OBJECT: usp_replicate_mo_header
-- DESCRIPTION: Replicate MO Headers (MOP10100) into h_mo_header. Append-only, active MOs only.
-- STATUS: active

CREATE PROCEDURE dbo.usp_replicate_mo_header
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH config AS (
        SELECT
            mo_status_active   = CAST(2 AS SMALLINT),
            mo_status_released = CAST(3 AS SMALLINT)
    )

    INSERT INTO dbo.h_mo_header
    (
        MANUFACTUREORDER_I, WORKORDERNUMBER, STATUS, MANUFACTUREORDERT,
        ITEMNMBR, LOCNCODE, DUEDATE, STARTDATE, TRACK, FGIINDX, FGNINDX,
        SCRAPAMNT, SOURCERES_I, QTYORDER, QTYREMAINING, QTYCOMPLETED,
        QTYREJECTED, DATERECD, REFTONMBRS, BCKTYEAR_I, BCKTPERIOD_I,
        REVISION, LOTATTRIBUTE1, LOTATTRIBUTE2, LOTATTRIBUTE3,
        CREATEDDATETIME, MODIFIEDDATETIME, DATETIMESTAMP
    )
    SELECT
        src.MANUFACTUREORDER_I, src.WORKORDERNUMBER, src.STATUS, src.MANUFACTUREORDERT,
        src.ITEMNMBR, src.LOCNCODE, src.DUEDATE, src.STARTDATE, src.TRACK, src.FGIINDX, src.FGNINDX,
        src.SCRAPAMNT, src.SOURCERES_I, src.QTYORDER, src.QTYREMAINING, src.QTYCOMPLETED,
        src.QTYREJECTED, src.DATERECD, src.REFTONMBRS, src.BCKTYEAR_I, src.BCKTPERIOD_I,
        src.REVISION, src.LOTATTRIBUTE1, src.LOTATTRIBUTE2, src.LOTATTRIBUTE3,
        src.CREATEDDATETIME, src.MODIFIEDDATETIME, GETUTCDATE()
    FROM dbo.MOP10100 AS src
    CROSS JOIN config
    WHERE src.MANUFACTUREORDERST_I IN (config.mo_status_active, config.mo_status_released)
      AND NOT EXISTS (
          SELECT 1 FROM dbo.h_mo_header AS tgt
          WHERE tgt.MANUFACTUREORDER_I = src.MANUFACTUREORDER_I
      );

    EXEC dbo.usp_rep_log;
END
GO